apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL-OLTP
    type: postgres
    access: proxy
    url: postgres:5432
    database: stripe_oltp
    user: stripe
    secureJsonData:
      password: stripe_pwd
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    editable: true

  - name: ClickHouse-OLAP
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: stripe_olap
      port: 8123
      server: clickhouse
    editable: true
